services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel_db
      - DB_USERNAME=alvaroadmin
      - DB_PASSWORD=1234
    command: ["apache2-foreground"] 
    entrypoint: ["/docker-entrypoint.sh"]

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: alvaroadmin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro

volumes:
  db_data:

